import { Model } from "mongoose";
import { Recipe, RecipeDocument } from "./schemas/recipe.schema";
import { Ingredient, IngredientDocument } from "./schemas/ingredient.schema";

export const INITIAL_RECIPES: Partial<Recipe>[] = [
  {
    slug: "butter-chicken-murgh-makhani",
    name: "Classic Butter Chicken (Murgh Makhani)",
    description: "Tender tandoori-spiced chicken simmered in a velvety, buttery tomato gravy infused with fenugreek and warm spices.",
    cuisine: "North Indian",
    mealTypes: ["Dinner", "Lunch"],
    dietaryTags: ["Non-Vegetarian", "Gluten-Free"],
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 4,
    nutrition: { calories: 520, protein: 38, carbs: 14, fat: 34, fiber: 3 },
    allergens: ["Dairy"],
    equipment: ["Heavy Bottom Pan", "Blender", "Whisk"],
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=900&auto=format&fit=crop&q=80",
    youtubeSearchQuery: "authentic butter chicken recipe Sanjeev Kapoor Ranveer Brar",
    tips: [
      "Lightly toast dried kasuri methi on a dry pan before crushing between your palms for maximum aroma.",
      "Strain the blended tomato puree through a fine sieve for that signature silky restaurant texture.",
    ],
    substitutions: [
      { ingredient: "Heavy Cream", substitute: "Cashew cream", note: "Soak 15 cashews in warm water and blend till smooth." },
      { ingredient: "Chicken Thighs", substitute: "Paneer cubes or Tofu", note: "Pan-fry lightly before adding to the gravy." },
    ],
    ingredients: [
      { name: "Boneless Chicken Thighs", normalizedName: "chicken", quantity: "600", unit: "g", optional: false, category: "poultry" },
      { name: "Ripe Roma Tomatoes", normalizedName: "tomato", quantity: "5", unit: "pieces", optional: false, category: "produce" },
      { name: "Butter (unsalted)", normalizedName: "butter", quantity: "50", unit: "g", optional: false, category: "dairy" },
      { name: "Heavy Cream", normalizedName: "cream", quantity: "60", unit: "ml", optional: false, category: "dairy" },
      { name: "Ginger Garlic Paste", normalizedName: "ginger garlic paste", quantity: "2", unit: "tbsp", optional: false, category: "condiments" },
      { name: "Kashmiri Red Chilli Powder", normalizedName: "chilli powder", quantity: "1.5", unit: "tbsp", optional: false, category: "spices" },
      { name: "Garam Masala", normalizedName: "garam masala", quantity: "1", unit: "tsp", optional: false, category: "spices" },
      { name: "Kasuri Methi (Dried Fenugreek)", normalizedName: "kasuri methi", quantity: "1", unit: "tbsp", optional: false, category: "spices" },
      { name: "Honey or Sugar", normalizedName: "sugar", quantity: "1", unit: "tsp", optional: true, category: "baking" },
      { name: "Salt", normalizedName: "salt", quantity: "1", unit: "tsp", optional: false, category: "spices" },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: "Marinate chicken pieces with ginger-garlic paste, 1 tbsp Kashmiri chilli powder, salt, and yogurt for 30 minutes.",
        timerMinutes: 30,
        chefTip: "Marinating in yogurt tenderizes the meat fibers evenly.",
        requiredEquipment: ["Mixing Bowl"],
      },
      {
        stepNumber: 2,
        instruction: "Sear marinated chicken on high heat in 1 tbsp oil until lightly charred and 80% cooked. Set aside.",
        timerMinutes: 8,
        chefTip: "Do not overcrowd the pan so chicken chars instead of steaming.",
        requiredEquipment: ["Skillet"],
      },
      {
        stepNumber: 3,
        instruction: "In the same pan, simmer chopped tomatoes with garlic, cardamom, and water for 15 minutes. Blend until smooth and strain back into pan.",
        timerMinutes: 15,
        chefTip: "Straining eliminates seeds and skins for a satin-like mouthfeel.",
        requiredEquipment: ["Blender", "Fine Strainer"],
      },
      {
        stepNumber: 4,
        instruction: "Whisk butter and cream into the simmering sauce. Slide in the seared chicken pieces and simmer gently for 8 minutes.",
        timerMinutes: 8,
        chefTip: "Keep heat on low when adding dairy to avoid breaking the sauce.",
        requiredEquipment: ["Saucepan"],
      },
      {
        stepNumber: 5,
        instruction: "Finish with crushed kasuri methi, garam masala, and a drizzle of cream. Serve hot with warm butter naan or steamed basmati rice.",
        timerMinutes: 2,
        chefTip: "Crush kasuri methi gently between warm palms right over the pot.",
        requiredEquipment: [],
      },
    ],
    averageRating: 4.8,
    ratingCount: 12,
    cookCount: 85,
    searchKeywords: ["chicken", "curry", "makhani", "north indian", "dinner", "rich", "party"],
    status: "published",
    version: 1,
  },
  {
    slug: "goan-fish-curry",
    name: "Goan Coconut Fish Curry",
    description: "Traditional coastal Goan curry cooked with fresh kingfish or pomfret, ground coconut, fiery dried red chillies, and tangy dried kokum.",
    cuisine: "Goan",
    mealTypes: ["Lunch", "Dinner"],
    dietaryTags: ["Non-Vegetarian", "Gluten-Free", "Dairy-Free"],
    difficulty: "Medium",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 3,
    nutrition: { calories: 380, protein: 32, carbs: 9, fat: 24, fiber: 3 },
    allergens: ["Fish"],
    equipment: ["Earthen Pot or Clay Pot", "Heavy Bottom Kadai", "Blender"],
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=900&auto=format&fit=crop&q=80",
    youtubeSearchQuery: "authentic goan fish curry recipe Chef Floyd Cardoz",
    tips: [
      "Kokum (dried mangosteen rind) provides the quintessential coastal tartness. Tamarind pulp is the best substitute if unavailable.",
      "Never boil the curry rapidly once coconut milk and delicate fish fillets are added.",
    ],
    substitutions: [
      { ingredient: "Kokum Petals", substitute: "Tamarind paste", note: "Use 1 tbsp dissolved tamarind pulp." },
      { ingredient: "Kingfish", substitute: "Pomfret, Salmon or Large Prawns", note: "Cook delicate prawns for only 3-4 minutes." },
    ],
    ingredients: [
      { name: "Fresh Kingfish or Pomfret Steaks", normalizedName: "fish", quantity: "450", unit: "g", optional: false, category: "seafood" },
      { name: "Fresh Grated Coconut", normalizedName: "coconut", quantity: "1", unit: "cup", optional: false, category: "produce" },
      { name: "Dried Kashmiri Chillies", normalizedName: "dry chilli", quantity: "6", unit: "pieces", optional: false, category: "spices" },
      { name: "Coriander Seeds", normalizedName: "coriander seeds", quantity: "1", unit: "tbsp", optional: false, category: "spices" },
      { name: "Cumin Seeds", normalizedName: "cumin", quantity: "1", unit: "tsp", optional: false, category: "spices" },
      { name: "Garlic Cloves", normalizedName: "garlic", quantity: "5", unit: "cloves", optional: false, category: "produce" },
      { name: "Kokum Petals", normalizedName: "kokum", quantity: "4", unit: "pieces", optional: false, category: "condiments" },
      { name: "Green Chillies (slit)", normalizedName: "green chilli", quantity: "2", unit: "pieces", optional: false, category: "produce" },
      { name: "Turmeric Powder", normalizedName: "turmeric", quantity: "0.5", unit: "tsp", optional: false, category: "spices" },
      { name: "Coconut Oil", normalizedName: "coconut oil", quantity: "1.5", unit: "tbsp", optional: false, category: "oils" },
      { name: "Salt", normalizedName: "salt", quantity: "1", unit: "tsp", optional: false, category: "spices" },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: "Soak kokum petals in 1/4 cup warm water. Salt the fish steaks lightly with turmeric and set aside.",
        timerMinutes: 10,
        chefTip: "Salting fish firms the flesh so it holds shape in simmering broth.",
        requiredEquipment: ["Small Bowl"],
      },
      {
        stepNumber: 2,
        instruction: "Blend grated coconut, dried chillies, coriander seeds, cumin, turmeric, and garlic with 1/2 cup water to a silky, fine orange masala paste.",
        timerMinutes: 5,
        chefTip: "Grind very finely until no coconut grits remain on fingers.",
        requiredEquipment: ["High-speed Blender"],
      },
      {
        stepNumber: 3,
        instruction: "Heat coconut oil in an earthen pot. Add slit green chillies and pour in the ground coconut paste with 1.5 cups water.",
        timerMinutes: 5,
        chefTip: "Simmer on low-medium heat until the raw spice aroma completely mellows.",
        requiredEquipment: ["Clay Pot or Kadai"],
      },
      {
        stepNumber: 4,
        instruction: "Gently drop in the soaked kokum with its water. Slide in the fish steaks one by one and gently shake the pot rather than stirring with a spoon.",
        timerMinutes: 7,
        chefTip: "Stirring with a spoon will break delicate fish fillets. Swirl the pan by its handles.",
        requiredEquipment: [],
      },
      {
        stepNumber: 5,
        instruction: "Simmer on low heat for 6-7 minutes until fish is cooked through and flaky. Rest 10 minutes before serving over hot Ukda red rice.",
        timerMinutes: 10,
        chefTip: "Goan curry tastes even better after resting as fish absorbs the kokum tang.",
        requiredEquipment: [],
      },
    ],
    averageRating: 4.9,
    ratingCount: 9,
    cookCount: 42,
    searchKeywords: ["fish", "goan", "seafood", "coastal", "curry", "coconut", "tangy"],
    status: "published",
    version: 1,
  },
  {
    slug: "paneer-butter-masala",
    name: "Restaurant Style Paneer Butter Masala",
    description: "Creamy, mildly sweet and savory curry with golden paneer cubes folded into a rich tomato, butter, and cashew nut gravy.",
    cuisine: "North Indian",
    mealTypes: ["Dinner", "Lunch"],
    dietaryTags: ["Vegetarian", "Gluten-Free"],
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    nutrition: { calories: 440, protein: 18, carbs: 16, fat: 34, fiber: 4 },
    allergens: ["Dairy", "Nuts"],
    equipment: ["Kadai", "Blender"],
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=900&auto=format&fit=crop&q=80",
    youtubeSearchQuery: "restaurant style paneer butter masala Ranveer Brar",
    tips: [
      "Soak paneer cubes in warm salted water for 10 minutes prior to cooking so they remain exceptionally soft.",
      "Cashew nuts provide natural richness and body without curdling the sauce.",
    ],
    substitutions: [
      { ingredient: "Paneer", substitute: "Extra firm Tofu", note: "Press tofu well and pan-sear with a pinch of turmeric." },
      { ingredient: "Cashews", substitute: "Melon seeds (Magaz)", note: "Equal weight provides identical smooth body." },
    ],
    ingredients: [
      { name: "Fresh Paneer", normalizedName: "paneer", quantity: "300", unit: "g", optional: false, category: "dairy" },
      { name: "Tomatoes (chopped)", normalizedName: "tomato", quantity: "4", unit: "pieces", optional: false, category: "produce" },
      { name: "Cashews (raw)", normalizedName: "cashew", quantity: "15", unit: "pieces", optional: false, category: "nuts" },
      { name: "Butter", normalizedName: "butter", quantity: "3", unit: "tbsp", optional: false, category: "dairy" },
      { name: "Fresh Cream", normalizedName: "cream", quantity: "2", unit: "tbsp", optional: false, category: "dairy" },
      { name: "Onion (chopped)", normalizedName: "onion", quantity: "1", unit: "pieces", optional: false, category: "produce" },
      { name: "Ginger Garlic Paste", normalizedName: "ginger garlic paste", quantity: "1", unit: "tbsp", optional: false, category: "condiments" },
      { name: "Kasuri Methi", normalizedName: "kasuri methi", quantity: "1", unit: "tsp", optional: false, category: "spices" },
      { name: "Kashmiri Chilli Powder", normalizedName: "chilli powder", quantity: "1", unit: "tbsp", optional: false, category: "spices" },
      { name: "Garam Masala", normalizedName: "garam masala", quantity: "0.5", unit: "tsp", optional: false, category: "spices" },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: "Cut paneer into bite-sized cubes and immerse in a bowl of warm water with a pinch of salt.",
        timerMinutes: 10,
        chefTip: "Warm water bath prevents paneer from turning rubbery in the hot gravy.",
        requiredEquipment: ["Bowl"],
      },
      {
        stepNumber: 2,
        instruction: "Saute onions, tomatoes, and cashews in 1 tbsp butter until soft. Cool and puree into a smooth sauce.",
        timerMinutes: 10,
        chefTip: "Let vegetables cool slightly before blending to prevent kitchen steam accidents.",
        requiredEquipment: ["Blender", "Pan"],
      },
      {
        stepNumber: 3,
        instruction: "Melt remaining butter in the pan, add ginger-garlic paste and chilli powder on low heat for 30 seconds.",
        timerMinutes: 1,
        chefTip: "Low heat prevents chilli powder from scorching and turning bitter.",
        requiredEquipment: ["Kadai"],
      },
      {
        stepNumber: 4,
        instruction: "Pour the tomato-cashew puree into the pan. Simmer for 8 minutes until oil glistens on the surface.",
        timerMinutes: 8,
        chefTip: "Watch for small bubbles and a glossy surface film.",
        requiredEquipment: [],
      },
      {
        stepNumber: 5,
        instruction: "Drain paneer cubes and fold into the curry. Finish with fresh cream, crushed kasuri methi, and garam masala.",
        timerMinutes: 3,
        chefTip: "Stir gently so paneer cubes retain their clean geometric edges.",
        requiredEquipment: [],
      },
    ],
    averageRating: 4.7,
    ratingCount: 15,
    cookCount: 110,
    searchKeywords: ["paneer", "vegetarian", "curry", "butter masala", "north indian", "dinner"],
    status: "published",
    version: 1,
  },
  {
    slug: "spaghetti-aglio-e-olio",
    name: "Classic Spaghetti Aglio e Olio",
    description: "The timeless Neapolitan pasta featuring golden toasted garlic, red pepper flakes, cold-pressed olive oil, and fresh flat-leaf parsley emulsified with starchy pasta water.",
    cuisine: "Italian",
    mealTypes: ["Dinner", "Lunch"],
    dietaryTags: ["Vegetarian", "Vegan"],
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 12,
    totalTime: 17,
    servings: 2,
    nutrition: { calories: 410, protein: 12, carbs: 58, fat: 16, fiber: 3 },
    allergens: ["Gluten"],
    equipment: ["Pasta Pot", "Wide Sauté Pan", "Tongs"],
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=900&auto=format&fit=crop&q=80",
    youtubeSearchQuery: "authentic spaghetti aglio e olio Vincenzo's Plate",
    tips: [
      "Slice the garlic thinly rather than mincing. Toasted garlic slices give gentle sweet crunch without burning.",
      "The emulsification of extra virgin olive oil with salty starchy pasta water creates the silky sauce.",
    ],
    substitutions: [
      { ingredient: "Spaghetti", substitute: "Linguine or Bucatini", note: "Long strand pasta catches emulsified oil best." },
      { ingredient: "Red Chilli Flakes", substitute: "Fresh minced red bird's eye chilli", note: "Provides clean floral heat." },
    ],
    ingredients: [
      { name: "Spaghetti", normalizedName: "pasta", quantity: "200", unit: "g", optional: false, category: "grains" },
      { name: "Extra Virgin Olive Oil", normalizedName: "olive oil", quantity: "4", unit: "tbsp", optional: false, category: "oils" },
      { name: "Garlic (thinly sliced)", normalizedName: "garlic", quantity: "6", unit: "cloves", optional: false, category: "produce" },
      { name: "Red Pepper Flakes (chilli flakes)", normalizedName: "chilli flakes", quantity: "1", unit: "tsp", optional: false, category: "spices" },
      { name: "Fresh Flat-Leaf Parsley (chopped)", normalizedName: "parsley", quantity: "3", unit: "tbsp", optional: false, category: "herbs" },
      { name: "Sea Salt", normalizedName: "salt", quantity: "1", unit: "tbsp", optional: false, category: "spices" },
      { name: "Lemon Zest (optional)", normalizedName: "lemon", quantity: "0.5", unit: "tsp", optional: true, category: "produce" },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: "Bring a large pot of water to a rolling boil. Season generously with salt until it tastes like the sea. Drop in spaghetti.",
        timerMinutes: 9,
        chefTip: "Cook pasta 1-2 minutes shy of al dente; it will finish cooking in the olive oil pan.",
        requiredEquipment: ["Pasta Pot"],
      },
      {
        stepNumber: 2,
        instruction: "In a wide cold pan, combine olive oil and thinly sliced garlic. Turn heat to medium-low to slowly infuse the oil without browning too quickly.",
        timerMinutes: 4,
        chefTip: "Starting garlic in cold oil prevents sharp bitter edges.",
        requiredEquipment: ["Wide Pan"],
      },
      {
        stepNumber: 3,
        instruction: "Once garlic slices turn pale straw-golden, immediately sprinkle red chilli flakes and remove pan briefly from direct heat.",
        timerMinutes: 1,
        chefTip: "Garlic continues cooking in residual oil heat; do not let it turn dark brown.",
        requiredEquipment: [],
      },
      {
        stepNumber: 4,
        instruction: "Scoop 1/2 cup of boiling starchy pasta water and whisk into the warm garlic oil to emulsify. Transfer spaghetti directly into the pan using tongs.",
        timerMinutes: 2,
        chefTip: "Starch in pasta water acts as a natural binder for the oil sauce.",
        requiredEquipment: ["Tongs"],
      },
      {
        stepNumber: 5,
        instruction: "Toss vigorously over medium heat until a glossy sauce coats every strand. Fold in fresh chopped parsley and serve immediately.",
        timerMinutes: 1,
        chefTip: "Serve right away while hot and glossy.",
        requiredEquipment: [],
      },
    ],
    averageRating: 4.9,
    ratingCount: 18,
    cookCount: 95,
    searchKeywords: ["pasta", "italian", "spaghetti", "quick", "15 minute", "vegan", "garlic", "dinner"],
    status: "published",
    version: 1,
  },
  {
    slug: "dal-makhani",
    name: "Slow Simmered Dal Makhani",
    description: "Authentic Punjab-style black lentils and red kidney beans slow-cooked with fresh ginger, tomatoes, butter, and cream.",
    cuisine: "North Indian",
    mealTypes: ["Dinner", "Lunch"],
    dietaryTags: ["Vegetarian", "Gluten-Free"],
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 60,
    totalTime: 80,
    servings: 5,
    nutrition: { calories: 360, protein: 16, carbs: 38, fat: 18, fiber: 10 },
    allergens: ["Dairy"],
    equipment: ["Pressure Cooker or Dutch Oven", "Potato Masher"],
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=900&auto=format&fit=crop&q=80",
    youtubeSearchQuery: "authentic dal makhani Ranveer Brar",
    tips: [
      "Lightly mashing a third of the cooked dal against the side of the pot creates natural creamy thickness.",
      "A small piece of butter added at the very end gives a brilliant sheen and fresh aromatic finish.",
    ],
    substitutions: [
      { ingredient: "Black Urad Dal", substitute: "Whole brown lentils", note: "Brown lentils cook slightly faster." },
      { ingredient: "Butter", substitute: "Vegan butter or pure coconut cream", note: "Keeps the recipe 100% plant-based." },
    ],
    ingredients: [
      { name: "Whole Black Urad Dal (soaked)", normalizedName: "urad dal", quantity: "1", unit: "cup", optional: false, category: "grains" },
      { name: "Rajma (Red Kidney Beans soaked)", normalizedName: "rajma", quantity: "0.25", unit: "cup", optional: false, category: "grains" },
      { name: "Tomato Puree", normalizedName: "tomato puree", quantity: "1", unit: "cup", optional: false, category: "condiments" },
      { name: "Butter (unsalted)", normalizedName: "butter", quantity: "50", unit: "g", optional: false, category: "dairy" },
      { name: "Fresh Cream", normalizedName: "cream", quantity: "4", unit: "tbsp", optional: false, category: "dairy" },
      { name: "Ginger (finely julienned)", normalizedName: "ginger", quantity: "1", unit: "tbsp", optional: false, category: "produce" },
      { name: "Kashmiri Chilli Powder", normalizedName: "chilli powder", quantity: "1", unit: "tbsp", optional: false, category: "spices" },
      { name: "Garam Masala", normalizedName: "garam masala", quantity: "0.5", unit: "tsp", optional: false, category: "spices" },
      { name: "Kasuri Methi", normalizedName: "kasuri methi", quantity: "1", unit: "tsp", optional: false, category: "spices" },
      { name: "Salt", normalizedName: "salt", quantity: "1.5", unit: "tsp", optional: false, category: "spices" },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: "Pressure cook soaked urad dal and rajma with 4 cups water, salt, and half the ginger until completely soft and creamy.",
        timerMinutes: 35,
        chefTip: "Lentils must mash effortlessly between thumb and forefinger.",
        requiredEquipment: ["Pressure Cooker"],
      },
      {
        stepNumber: 2,
        instruction: "In a separate pot, melt 2 tbsp butter, add remaining ginger and chilli powder, followed by tomato puree. Cook for 8 minutes.",
        timerMinutes: 8,
        chefTip: "Cook tomato puree until fat begins to release along pan borders.",
        requiredEquipment: ["Pot"],
      },
      {
        stepNumber: 3,
        instruction: "Combine cooked dal with the tomato mixture. Lightly mash portions of dal with the back of a ladle to release starch.",
        timerMinutes: 5,
        chefTip: "Natural starch release prevents watery separation.",
        requiredEquipment: ["Ladle"],
      },
      {
        stepNumber: 4,
        instruction: "Simmer on low heat for 25-30 minutes, stirring occasionally to prevent sticking to bottom.",
        timerMinutes: 25,
        chefTip: "Slow simmering unlocks the earthy nutty profile of black lentils.",
        requiredEquipment: [],
      },
      {
        stepNumber: 5,
        instruction: "Stir in remaining butter, fresh cream, crushed kasuri methi, and garam masala. Serve hot with garlic naan or jeera rice.",
        timerMinutes: 3,
        chefTip: "Rest 10 minutes before serving for maximum flavor integration.",
        requiredEquipment: [],
      },
    ],
    averageRating: 4.8,
    ratingCount: 14,
    cookCount: 78,
    searchKeywords: ["dal", "lentils", "makhani", "vegetarian", "north indian", "dinner", "high protein"],
    status: "published",
    version: 1,
  },
  {
    slug: "thai-green-curry-chicken",
    name: "Aromatic Thai Green Curry",
    description: "Vibrant coconut curry fragrant with lemongrass, kaffir lime, galangal, Thai green chillies, bamboo shoots, and tender chicken.",
    cuisine: "Pan-Asian",
    mealTypes: ["Dinner", "Lunch"],
    dietaryTags: ["Non-Vegetarian", "Gluten-Free", "Dairy-Free"],
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    nutrition: { calories: 430, protein: 32, carbs: 12, fat: 28, fiber: 4 },
    allergens: ["Fish (Fish Sauce)"],
    equipment: ["Wok or Deep Skillet"],
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=900&auto=format&fit=crop&q=80",
    youtubeSearchQuery: "authentic thai green curry recipe Hot Thai Kitchen",
    tips: [
      "Crack the coconut milk cream first in a hot wok until coconut oil separates before frying the green curry paste.",
      "Tear fresh Thai sweet basil leaves into the curry at the very last second and turn off the flame to preserve their emerald color.",
    ],
    substitutions: [
      { ingredient: "Chicken", substitute: "Crispy Tofu and Shiitake Mushrooms", note: "Wonderful plant-based version." },
      { ingredient: "Fish Sauce", substitute: "Soy Sauce or Tamari", note: "Use 1.5 tbsp light soy sauce for vegetarian umami." },
    ],
    ingredients: [
      { name: "Chicken Breast or Thighs (sliced)", normalizedName: "chicken", quantity: "500", unit: "g", optional: false, category: "poultry" },
      { name: "Thai Green Curry Paste", normalizedName: "green curry paste", quantity: "3", unit: "tbsp", optional: false, category: "condiments" },
      { name: "Coconut Milk (full fat)", normalizedName: "coconut milk", quantity: "400", unit: "ml", optional: false, category: "canned" },
      { name: "Eggplant (diced)", normalizedName: "eggplant", quantity: "1", unit: "cup", optional: false, category: "produce" },
      { name: "Bamboo Shoots", normalizedName: "bamboo shoots", quantity: "0.5", unit: "cup", optional: true, category: "canned" },
      { name: "Fish Sauce", normalizedName: "fish sauce", quantity: "1.5", unit: "tbsp", optional: false, category: "condiments" },
      { name: "Palm Sugar or Brown Sugar", normalizedName: "sugar", quantity: "1", unit: "tbsp", optional: false, category: "baking" },
      { name: "Thai Basil Leaves", normalizedName: "basil", quantity: "1", unit: "cup", optional: false, category: "herbs" },
      { name: "Kaffir Lime Leaves", normalizedName: "lime leaves", quantity: "4", unit: "leaves", optional: false, category: "herbs" },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: "Spoon 1/3 cup of thick coconut cream from top of can into a hot wok. Fry over medium-high heat until oil breaks out.",
        timerMinutes: 4,
        chefTip: "Cracking the coconut cream is the secret to authentic Thai curry depth.",
        requiredEquipment: ["Wok"],
      },
      {
        stepNumber: 2,
        instruction: "Add Thai green curry paste. Fry in the coconut oil for 2 minutes until intensely fragrant and oil turns green.",
        timerMinutes: 2,
        chefTip: "Frying blooms the aromatic herbs in the paste.",
        requiredEquipment: [],
      },
      {
        stepNumber: 3,
        instruction: "Add chicken slices and toss for 3 minutes to coat with the green curry paste.",
        timerMinutes: 3,
        chefTip: "Sear chicken until exterior turns opaque.",
        requiredEquipment: [],
      },
      {
        stepNumber: 4,
        instruction: "Pour in the remaining coconut milk, torn kaffir lime leaves, and diced eggplants. Simmer gently for 10 minutes.",
        timerMinutes: 10,
        chefTip: "Do not let curry boil furiously or coconut milk may separate.",
        requiredEquipment: [],
      },
      {
        stepNumber: 5,
        instruction: "Season with fish sauce and palm sugar. Remove from heat, fold in fresh Thai basil leaves, and serve with jasmine rice.",
        timerMinutes: 2,
        chefTip: "Residual heat wilts the basil while keeping its fresh sweetness.",
        requiredEquipment: [],
      },
    ],
    averageRating: 4.8,
    ratingCount: 11,
    cookCount: 52,
    searchKeywords: ["thai", "green curry", "coconut", "chicken", "asian", "quick dinner"],
    status: "published",
    version: 1,
  },
  {
    slug: "classic-shakshuka",
    name: "Smoky Tomato & Bell Pepper Shakshuka",
    description: "Gently poached eggs nestled in a spiced, chunky tomato, bell pepper, and garlic sauce with cumin, smoked paprika, and fresh cilantro.",
    cuisine: "Middle Eastern",
    mealTypes: ["Breakfast", "Brunch", "Dinner"],
    dietaryTags: ["Eggetarian", "Vegetarian", "Gluten-Free"],
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 2,
    nutrition: { calories: 290, protein: 15, carbs: 18, fat: 17, fiber: 5 },
    allergens: ["Eggs"],
    equipment: ["Cast Iron Skillet with Lid"],
    imageUrl: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=900&auto=format&fit=crop&q=80",
    youtubeSearchQuery: "authentic shakshuka recipe Ottolenghi",
    tips: [
      "Use the back of a spoon to create small wells in the bubbling tomato sauce before cracking each egg.",
      "Cover with a lid for 4-5 minutes so the egg whites set while the yolks remain lusciously runny.",
    ],
    substitutions: [
      { ingredient: "Eggs", substitute: "Silken Tofu or Chickpeas", note: "Spoon silken tofu dollops into wells for vegan shakshuka." },
      { ingredient: "Feta Cheese", substitute: "Crumbled Paneer or Goat Cheese", note: "Adds delicious creamy tang." },
    ],
    ingredients: [
      { name: "Fresh Eggs", normalizedName: "egg", quantity: "4", unit: "pieces", optional: false, category: "dairy" },
      { name: "Ripe Crushed Tomatoes", normalizedName: "tomato", quantity: "400", unit: "g", optional: false, category: "produce" },
      { name: "Red Bell Pepper (sliced)", normalizedName: "bell pepper", quantity: "1", unit: "pieces", optional: false, category: "produce" },
      { name: "Yellow Onion (diced)", normalizedName: "onion", quantity: "1", unit: "pieces", optional: false, category: "produce" },
      { name: "Garlic (minced)", normalizedName: "garlic", quantity: "3", unit: "cloves", optional: false, category: "produce" },
      { name: "Olive Oil", normalizedName: "olive oil", quantity: "2", unit: "tbsp", optional: false, category: "oils" },
      { name: "Ground Cumin", normalizedName: "cumin", quantity: "1", unit: "tsp", optional: false, category: "spices" },
      { name: "Smoked Paprika", normalizedName: "paprika", quantity: "1", unit: "tsp", optional: false, category: "spices" },
      { name: "Cilantro or Parsley (fresh)", normalizedName: "coriander", quantity: "2", unit: "tbsp", optional: false, category: "herbs" },
      { name: "Feta Cheese (crumbled)", normalizedName: "feta", quantity: "30", unit: "g", optional: true, category: "dairy" },
    ],
    steps: [
      {
        stepNumber: 1,
        instruction: "Heat olive oil in a cast iron skillet. Sauté onions and bell peppers over medium heat for 6 minutes until sweet and tender.",
        timerMinutes: 6,
        chefTip: "Letting peppers soften slowly sweetens the sauce naturally.",
        requiredEquipment: ["Cast Iron Skillet"],
      },
      {
        stepNumber: 2,
        instruction: "Add garlic, ground cumin, and smoked paprika. Stir continuously for 1 minute until spices bloom.",
        timerMinutes: 1,
        chefTip: "Paprika scorches quickly, stir continuously.",
        requiredEquipment: [],
      },
      {
        stepNumber: 3,
        instruction: "Pour in crushed tomatoes and simmer gently for 8 minutes until sauce thickens to spoonable consistency. Season with salt.",
        timerMinutes: 8,
        chefTip: "Ensure sauce is thick enough so eggs don't sink to the metal bottom.",
        requiredEquipment: [],
      },
      {
        stepNumber: 4,
        instruction: "Form 4 shallow wells in the sauce with a spoon. Crack an egg into each well. Cover pan with lid.",
        timerMinutes: 5,
        chefTip: "Covering traps gentle steam to cook egg whites evenly without overcooking yolks.",
        requiredEquipment: ["Pan Lid"],
      },
      {
        stepNumber: 5,
        instruction: "Cook for 4-5 minutes until whites are set and yolks wobble. Scatter crumbled feta and fresh cilantro. Serve with crusty sourdough bread.",
        timerMinutes: 1,
        chefTip: "Serve immediately while egg yolks are warm and runny.",
        requiredEquipment: [],
      },
    ],
    averageRating: 4.8,
    ratingCount: 16,
    cookCount: 92,
    searchKeywords: ["shakshuka", "eggs", "breakfast", "brunch", "quick", "middle eastern", "healthy"],
    status: "published",
    version: 1,
  }
];

export const INITIAL_INGREDIENTS: Partial<Ingredient>[] = [
  { name: "Chicken Breast / Thighs", normalizedName: "chicken", aliases: ["chicken breast", "chicken thighs", "boneless chicken", "murgh"], category: "poultry", defaultUnit: "g", commonUnits: ["g", "kg", "pieces"], defaultShelfLifeDays: 3 },
  { name: "Paneer", normalizedName: "paneer", aliases: ["cottage cheese", "indian cottage cheese", "chenna"], category: "dairy", defaultUnit: "g", commonUnits: ["g", "pieces"], defaultShelfLifeDays: 7 },
  { name: "Eggs", normalizedName: "egg", aliases: ["eggs", "anda", "whole eggs"], category: "dairy", defaultUnit: "pieces", commonUnits: ["pieces"], defaultShelfLifeDays: 21 },
  { name: "Fresh Tomatoes", normalizedName: "tomato", aliases: ["tomatoes", "tamatar", "roma tomato", "plum tomato"], category: "produce", defaultUnit: "pieces", commonUnits: ["pieces", "g"], defaultShelfLifeDays: 7 },
  { name: "Onions", normalizedName: "onion", aliases: ["onions", "pyaaz", "red onion", "yellow onion"], category: "produce", defaultUnit: "pieces", commonUnits: ["pieces", "kg"], defaultShelfLifeDays: 30 },
  { name: "Garlic", normalizedName: "garlic", aliases: ["lehsun", "garlic cloves", "garlic bulb"], category: "produce", defaultUnit: "cloves", commonUnits: ["cloves", "pieces"], defaultShelfLifeDays: 45 },
  { name: "Ginger", normalizedName: "ginger", aliases: ["adrak", "fresh ginger", "ginger root"], category: "produce", defaultUnit: "g", commonUnits: ["pieces", "tbsp", "g"], defaultShelfLifeDays: 21 },
  { name: "Bell Pepper / Capsicum", normalizedName: "capsicum", aliases: ["bell pepper", "green pepper", "sweet pepper", "shimla mirch", "red pepper"], category: "produce", defaultUnit: "pieces", commonUnits: ["pieces"], defaultShelfLifeDays: 10 },
  { name: "Green Chillies", normalizedName: "green chilli", aliases: ["green chilies", "hari mirch", "chilli"], category: "produce", defaultUnit: "pieces", commonUnits: ["pieces"], defaultShelfLifeDays: 10 },
  { name: "Fresh Coriander", normalizedName: "coriander", aliases: ["cilantro", "fresh coriander", "dhaniya", "coriander leaves", "kothmir"], category: "herbs", defaultUnit: "bunch", commonUnits: ["bunch", "tbsp"], defaultShelfLifeDays: 5 },
  { name: "Unsalted Butter", normalizedName: "butter", aliases: ["makhan", "unsalted butter", "salted butter"], category: "dairy", defaultUnit: "g", commonUnits: ["g", "tbsp"], defaultShelfLifeDays: 60 },
  { name: "Heavy Cream", normalizedName: "cream", aliases: ["heavy cream", "fresh cream", "malai", "whipping cream"], category: "dairy", defaultUnit: "ml", commonUnits: ["ml", "tbsp"], defaultShelfLifeDays: 10 },
  { name: "Spaghetti Pasta", normalizedName: "pasta", aliases: ["spaghetti", "penne", "fettuccine", "rigatoni"], category: "grains", defaultUnit: "g", commonUnits: ["g"], defaultShelfLifeDays: 365 },
  { name: "Extra Virgin Olive Oil", normalizedName: "olive oil", aliases: ["olive oil", "cooking oil", "extra virgin oil"], category: "oils", defaultUnit: "tbsp", commonUnits: ["tbsp", "ml"], defaultShelfLifeDays: 180 },
  { name: "Basmati Rice", normalizedName: "rice", aliases: ["basmati rice", "white rice", "brown rice", "chawal"], category: "grains", defaultUnit: "g", commonUnits: ["cups", "kg", "g"], defaultShelfLifeDays: 365 },
  { name: "Plain Yogurt / Curd", normalizedName: "curd", aliases: ["yogurt", "dahi", "plain yogurt", "greek yogurt"], category: "dairy", defaultUnit: "g", commonUnits: ["cups", "g"], defaultShelfLifeDays: 7 },
  { name: "Salt", normalizedName: "salt", aliases: ["table salt", "sea salt", "namak"], category: "spices", defaultUnit: "tsp", commonUnits: ["tsp", "tbsp"], defaultShelfLifeDays: 730 },
  { name: "Turmeric Powder", normalizedName: "turmeric", aliases: ["haldi", "turmeric powder"], category: "spices", defaultUnit: "tsp", commonUnits: ["tsp"], defaultShelfLifeDays: 365 },
  { name: "Kashmiri Chilli Powder", normalizedName: "chilli powder", aliases: ["chili powder", "red chili", "lal mirch", "paprika"], category: "spices", defaultUnit: "tsp", commonUnits: ["tbsp", "tsp"], defaultShelfLifeDays: 365 },
  { name: "Garam Masala", normalizedName: "garam masala", aliases: ["all spice mix", "curry powder"], category: "spices", defaultUnit: "tsp", commonUnits: ["tsp"], defaultShelfLifeDays: 365 },
  { name: "Cumin Seeds", normalizedName: "cumin", aliases: ["jeera", "cumin seeds"], category: "spices", defaultUnit: "tsp", commonUnits: ["tsp"], defaultShelfLifeDays: 365 },
  { name: "Fish Fillets", normalizedName: "fish", aliases: ["salmon", "cod", "pomfret", "surmai", "sea bass"], category: "seafood", defaultUnit: "g", commonUnits: ["g", "pieces"], defaultShelfLifeDays: 2 },
  { name: "Grated Coconut", normalizedName: "coconut", aliases: ["nariyal", "shredded coconut", "desiccated coconut"], category: "produce", defaultUnit: "g", commonUnits: ["cups", "g"], defaultShelfLifeDays: 5 },
  { name: "All-Purpose Flour / Maida", normalizedName: "maida", aliases: ["all-purpose flour", "all purpose flour", "plain flour", "white flour"], category: "pantry", defaultUnit: "g", commonUnits: ["g", "cups"], defaultShelfLifeDays: 180 },
];

export async function seedDatabaseIfEmpty(
  recipeModel: Model<RecipeDocument>,
  ingredientModel: Model<IngredientDocument>
) {
  try {
    const recipeCount = await recipeModel.countDocuments();
    if (recipeCount === 0) {
      console.log("Seeding authentic recipes into MongoDB Atlas...");
      for (const r of INITIAL_RECIPES) {
        const withDefaults = {
          ...r,
          category: (r as any).category || (r.mealTypes && r.mealTypes[0]) || "Main Course",
          instructions: (r as any).instructions || r.steps?.map((s) => s.instruction) || [],
          provider: "curated",
          lastSyncedAt: new Date(),
          popularityScore: 0,
        };
        await recipeModel.findOneAndUpdate({ slug: r.slug }, withDefaults, { upsert: true, returnDocument: 'after' });
      }
      console.log(`Seeded ${INITIAL_RECIPES.length} recipes.`);
    }

    const ingredientCount = await ingredientModel.countDocuments();
    if (ingredientCount === 0) {
      console.log("Seeding master ingredients catalog into MongoDB Atlas...");
      for (const ing of INITIAL_INGREDIENTS) {
        await ingredientModel.findOneAndUpdate({ normalizedName: ing.normalizedName }, ing, { upsert: true, returnDocument: 'after' });
      }
      console.log(`Seeded ${INITIAL_INGREDIENTS.length} master ingredients.`);
    }
  } catch (error) {
    console.warn("Database seed check notice:", error);
  }
}
